<?php

namespace WitnessData\FilamentCountry;

use Filament\Support\Contracts\HasLabel;
use Illuminate\Contracts\Support\Htmlable;

enum Country: string implements HasLabel
{
    case AF = 'AF';
    case AX = 'AX';
    case AL = 'AL';
    case DZ = 'DZ';
    case AS = 'AS';
    case AD = 'AD';
    case AO = 'AO';
    case AI = 'AI';
    case AQ = 'AQ';
    case AG = 'AG';
    case AR = 'AR';
    case AM = 'AM';
    case AW = 'AW';
    case AU = 'AU';
    case AT = 'AT';
    case AZ = 'AZ';
    case BS = 'BS';
    case BH = 'BH';
    case BD = 'BD';
    case BB = 'BB';
    case BY = 'BY';
    case BE = 'BE';
    case BZ = 'BZ';
    case BJ = 'BJ';
    case BM = 'BM';
    case BT = 'BT';
    case BO = 'BO';
    case BQ = 'BQ';
    case BA = 'BA';
    case BW = 'BW';
    case BV = 'BV';
    case BR = 'BR';
    case IO = 'IO';
    case BN = 'BN';
    case BG = 'BG';
    case BF = 'BF';
    case BI = 'BI';
    case CV = 'CV';
    case KH = 'KH';
    case CM = 'CM';
    case CA = 'CA';
    case KY = 'KY';
    case CF = 'CF';
    case TD = 'TD';
    case CL = 'CL';
    case CN = 'CN';
    case CX = 'CX';
    case CC = 'CC';
    case CO = 'CO';
    case KM = 'KM';
    case CG = 'CG';
    case CD = 'CD';
    case CK = 'CK';
    case CR = 'CR';
    case CI = 'CI';
    case HR = 'HR';
    case CU = 'CU';
    case CW = 'CW';
    case CY = 'CY';
    case CZ = 'CZ';
    case DK = 'DK';
    case DJ = 'DJ';
    case DM = 'DM';
    case DO = 'DO';
    case EC = 'EC';
    case EG = 'EG';
    case SV = 'SV';
    case GQ = 'GQ';
    case ER = 'ER';
    case EE = 'EE';
    case SZ = 'SZ';
    case ET = 'ET';
    case FK = 'FK';
    case FO = 'FO';
    case FJ = 'FJ';
    case FI = 'FI';
    case FR = 'FR';
    case GF = 'GF';
    case PF = 'PF';
    case TF = 'TF';
    case GA = 'GA';
    case GM = 'GM';
    case GE = 'GE';
    case DE = 'DE';
    case GH = 'GH';
    case GI = 'GI';
    case GR = 'GR';
    case GL = 'GL';
    case GD = 'GD';
    case GP = 'GP';
    case GU = 'GU';
    case GT = 'GT';
    case GG = 'GG';
    case GN = 'GN';
    case GW = 'GW';
    case GY = 'GY';
    case HT = 'HT';
    case HM = 'HM';
    case VA = 'VA';
    case HN = 'HN';
    case HK = 'HK';
    case HU = 'HU';
    case IS = 'IS';
    case IN = 'IN';
    case ID = 'ID';
    case IR = 'IR';
    case IQ = 'IQ';
    case IE = 'IE';
    case IM = 'IM';
    case IL = 'IL';
    case IT = 'IT';
    case JM = 'JM';
    case JP = 'JP';
    case JE = 'JE';
    case JO = 'JO';
    case KZ = 'KZ';
    case KE = 'KE';
    case KI = 'KI';
    case KP = 'KP';
    case KR = 'KR';
    case KW = 'KW';
    case KG = 'KG';
    case LA = 'LA';
    case LV = 'LV';
    case LB = 'LB';
    case LS = 'LS';
    case LR = 'LR';
    case LY = 'LY';
    case LI = 'LI';
    case LT = 'LT';
    case LU = 'LU';
    case MO = 'MO';
    case MG = 'MG';
    case MW = 'MW';
    case MY = 'MY';
    case MV = 'MV';
    case ML = 'ML';
    case MT = 'MT';
    case MH = 'MH';
    case MQ = 'MQ';
    case MR = 'MR';
    case MU = 'MU';
    case YT = 'YT';
    case MX = 'MX';
    case FM = 'FM';
    case MD = 'MD';
    case MC = 'MC';
    case MN = 'MN';
    case ME = 'ME';
    case MS = 'MS';
    case MA = 'MA';
    case MZ = 'MZ';
    case MM = 'MM';
    case NA = 'NA';
    case NR = 'NR';
    case NP = 'NP';
    case NL = 'NL';
    case NC = 'NC';
    case NZ = 'NZ';
    case NI = 'NI';
    case NE = 'NE';
    case NG = 'NG';
    case NU = 'NU';
    case NF = 'NF';
    case MK = 'MK';
    case MP = 'MP';
    case NO = 'NO';
    case OM = 'OM';
    case PK = 'PK';
    case PW = 'PW';
    case PS = 'PS';
    case PA = 'PA';
    case PG = 'PG';
    case PY = 'PY';
    case PE = 'PE';
    case PH = 'PH';
    case PN = 'PN';
    case PL = 'PL';
    case PT = 'PT';
    case PR = 'PR';
    case QA = 'QA';
    case RE = 'RE';
    case RO = 'RO';
    case RU = 'RU';
    case RW = 'RW';
    case BL = 'BL';
    case SH = 'SH';
    case KN = 'KN';
    case LC = 'LC';
    case MF = 'MF';
    case PM = 'PM';
    case VC = 'VC';
    case WS = 'WS';
    case SM = 'SM';
    case ST = 'ST';
    case SA = 'SA';
    case SN = 'SN';
    case RS = 'RS';
    case SC = 'SC';
    case SL = 'SL';
    case SG = 'SG';
    case SX = 'SX';
    case SK = 'SK';
    case SI = 'SI';
    case SB = 'SB';
    case SO = 'SO';
    case ZA = 'ZA';
    case GS = 'GS';
    case SS = 'SS';
    case ES = 'ES';
    case LK = 'LK';
    case SD = 'SD';
    case SR = 'SR';
    case SJ = 'SJ';
    case SE = 'SE';
    case CH = 'CH';
    case SY = 'SY';
    case TW = 'TW';
    case TJ = 'TJ';
    case TZ = 'TZ';
    case TH = 'TH';
    case TL = 'TL';
    case TG = 'TG';
    case TK = 'TK';
    case TO = 'TO';
    case TT = 'TT';
    case TN = 'TN';
    case TR = 'TR';
    case TM = 'TM';
    case TC = 'TC';
    case TV = 'TV';
    case UG = 'UG';
    case UA = 'UA';
    case AE = 'AE';
    case GB = 'GB';
    case US = 'US';
    case UM = 'UM';
    case UY = 'UY';
    case UZ = 'UZ';
    case VU = 'VU';
    case VE = 'VE';
    case VN = 'VN';
    case VG = 'VG';
    case VI = 'VI';
    case WF = 'WF';
    case EH = 'EH';
    case YE = 'YE';
    case ZM = 'ZM';
    case ZW = 'ZW';

    public function getName(): string
    {
        return match ($this) {
            self::AF => __('Afghanistan'),
            self::AX => __('Åland Islands'),
            self::AL => __('Albania'),
            self::DZ => __('Algeria'),
            self::AS => __('American Samoa'),
            self::AD => __('Andorra'),
            self::AO => __('Angola'),
            self::AI => __('Anguilla'),
            self::AQ => __('Antarctica'),
            self::AG => __('Antigua and Barbuda'),
            self::AR => __('Argentina'),
            self::AM => __('Armenia'),
            self::AW => __('Aruba'),
            self::AU => __('Australia'),
            self::AT => __('Austria'),
            self::AZ => __('Azerbaijan'),
            self::BS => __('Bahamas'),
            self::BH => __('Bahrain'),
            self::BD => __('Bangladesh'),
            self::BB => __('Barbados'),
            self::BY => __('Belarus'),
            self::BE => __('Belgium'),
            self::BZ => __('Belize'),
            self::BJ => __('Benin'),
            self::BM => __('Bermuda'),
            self::BT => __('Bhutan'),
            self::BO => __('Bolivia, Plurinational State of'),
            self::BQ => __('Bonaire, Sint Eustatius and Saba'),
            self::BA => __('Bosnia and Herzegovina'),
            self::BW => __('Botswana'),
            self::BV => __('Bouvet Island'),
            self::BR => __('Brazil'),
            self::IO => __('British Indian Ocean Territory'),
            self::BN => __('Brunei Darussalam'),
            self::BG => __('Bulgaria'),
            self::BF => __('Burkina Faso'),
            self::BI => __('Burundi'),
            self::CV => __('Cabo Verde'),
            self::KH => __('Cambodia'),
            self::CM => __('Cameroon'),
            self::CA => __('Canada'),
            self::KY => __('Cayman Islands'),
            self::CF => __('Central African Republic'),
            self::TD => __('Chad'),
            self::CL => __('Chile'),
            self::CN => __('China'),
            self::CX => __('Christmas Island'),
            self::CC => __('Cocos (Keeling) Islands'),
            self::CO => __('Colombia'),
            self::KM => __('Comoros'),
            self::CG => __('Congo'),
            self::CD => __('Congo, Democratic Republic of the'),
            self::CK => __('Cook Islands'),
            self::CR => __('Costa Rica'),
            self::CI => __('Côte d\'Ivoire'),
            self::HR => __('Croatia'),
            self::CU => __('Cuba'),
            self::CW => __('Curaçao'),
            self::CY => __('Cyprus'),
            self::CZ => __('Czechia'),
            self::DK => __('Denmark'),
            self::DJ => __('Djibouti'),
            self::DM => __('Dominica'),
            self::DO => __('Dominican Republic'),
            self::EC => __('Ecuador'),
            self::EG => __('Egypt'),
            self::SV => __('El Salvador'),
            self::GQ => __('Equatorial Guinea'),
            self::ER => __('Eritrea'),
            self::EE => __('Estonia'),
            self::SZ => __('Eswatini'),
            self::ET => __('Ethiopia'),
            self::FK => __('Falkland Islands (Malvinas)'),
            self::FO => __('Faroe Islands'),
            self::FJ => __('Fiji'),
            self::FI => __('Finland'),
            self::FR => __('France'),
            self::GF => __('French Guiana'),
            self::PF => __('French Polynesia'),
            self::TF => __('French Southern Territories'),
            self::GA => __('Gabon'),
            self::GM => __('Gambia'),
            self::GE => __('Georgia'),
            self::DE => __('Germany'),
            self::GH => __('Ghana'),
            self::GI => __('Gibraltar'),
            self::GR => __('Greece'),
            self::GL => __('Greenland'),
            self::GD => __('Grenada'),
            self::GP => __('Guadeloupe'),
            self::GU => __('Guam'),
            self::GT => __('Guatemala'),
            self::GG => __('Guernsey'),
            self::GN => __('Guinea'),
            self::GW => __('Guinea-Bissau'),
            self::GY => __('Guyana'),
            self::HT => __('Haiti'),
            self::HM => __('Heard Island and McDonald Islands'),
            self::VA => __('Holy See'),
            self::HN => __('Honduras'),
            self::HK => __('Hong Kong'),
            self::HU => __('Hungary'),
            self::IS => __('Iceland'),
            self::IN => __('India'),
            self::ID => __('Indonesia'),
            self::IR => __('Iran, Islamic Republic of'),
            self::IQ => __('Iraq'),
            self::IE => __('Ireland'),
            self::IM => __('Isle of Man'),
            self::IL => __('Israel'),
            self::IT => __('Italy'),
            self::JM => __('Jamaica'),
            self::JP => __('Japan'),
            self::JE => __('Jersey'),
            self::JO => __('Jordan'),
            self::KZ => __('Kazakhstan'),
            self::KE => __('Kenya'),
            self::KI => __('Kiribati'),
            self::KP => __('Korea, Democratic People\'s Republic of'),
            self::KR => __('Korea, Republic of'),
            self::KW => __('Kuwait'),
            self::KG => __('Kyrgyzstan'),
            self::LA => __('Lao People\'s Democratic Republic'),
            self::LV => __('Latvia'),
            self::LB => __('Lebanon'),
            self::LS => __('Lesotho'),
            self::LR => __('Liberia'),
            self::LY => __('Libya'),
            self::LI => __('Liechtenstein'),
            self::LT => __('Lithuania'),
            self::LU => __('Luxembourg'),
            self::MO => __('Macao'),
            self::MG => __('Madagascar'),
            self::MW => __('Malawi'),
            self::MY => __('Malaysia'),
            self::MV => __('Maldives'),
            self::ML => __('Mali'),
            self::MT => __('Malta'),
            self::MH => __('Marshall Islands'),
            self::MQ => __('Martinique'),
            self::MR => __('Mauritania'),
            self::MU => __('Mauritius'),
            self::YT => __('Mayotte'),
            self::MX => __('Mexico'),
            self::FM => __('Micronesia, Federated States of'),
            self::MD => __('Moldova, Republic of'),
            self::MC => __('Monaco'),
            self::MN => __('Mongolia'),
            self::ME => __('Montenegro'),
            self::MS => __('Montserrat'),
            self::MA => __('Morocco'),
            self::MZ => __('Mozambique'),
            self::MM => __('Myanmar'),
            self::NA => __('Namibia'),
            self::NR => __('Nauru'),
            self::NP => __('Nepal'),
            self::NL => __('Netherlands, Kingdom of the'),
            self::NC => __('New Caledonia'),
            self::NZ => __('New Zealand'),
            self::NI => __('Nicaragua'),
            self::NE => __('Niger'),
            self::NG => __('Nigeria'),
            self::NU => __('Niue'),
            self::NF => __('Norfolk Island'),
            self::MK => __('North Macedonia'),
            self::MP => __('Northern Mariana Islands'),
            self::NO => __('Norway'),
            self::OM => __('Oman'),
            self::PK => __('Pakistan'),
            self::PW => __('Palau'),
            self::PS => __('Palestine, State of'),
            self::PA => __('Panama'),
            self::PG => __('Papua New Guinea'),
            self::PY => __('Paraguay'),
            self::PE => __('Peru'),
            self::PH => __('Philippines'),
            self::PN => __('Pitcairn'),
            self::PL => __('Poland'),
            self::PT => __('Portugal'),
            self::PR => __('Puerto Rico'),
            self::QA => __('Qatar'),
            self::RE => __('Réunion'),
            self::RO => __('Romania'),
            self::RU => __('Russian Federation'),
            self::RW => __('Rwanda'),
            self::BL => __('Saint Barthélemy'),
            self::SH => __('Saint Helena, Ascension and Tristan da Cunha'),
            self::KN => __('Saint Kitts and Nevis'),
            self::LC => __('Saint Lucia'),
            self::MF => __('Saint Martin (French part)'),
            self::PM => __('Saint Pierre and Miquelon'),
            self::VC => __('Saint Vincent and the Grenadines'),
            self::WS => __('Samoa'),
            self::SM => __('San Marino'),
            self::ST => __('Sao Tome and Principe'),
            self::SA => __('Saudi Arabia'),
            self::SN => __('Senegal'),
            self::RS => __('Serbia'),
            self::SC => __('Seychelles'),
            self::SL => __('Sierra Leone'),
            self::SG => __('Singapore'),
            self::SX => __('Sint Maarten (Dutch part)'),
            self::SK => __('Slovakia'),
            self::SI => __('Slovenia'),
            self::SB => __('Solomon Islands'),
            self::SO => __('Somalia'),
            self::ZA => __('South Africa'),
            self::GS => __('South Georgia and the South Sandwich Islands'),
            self::SS => __('South Sudan'),
            self::ES => __('Spain'),
            self::LK => __('Sri Lanka'),
            self::SD => __('Sudan'),
            self::SR => __('Suriname'),
            self::SJ => __('Svalbard and Jan Mayen'),
            self::SE => __('Sweden'),
            self::CH => __('Switzerland'),
            self::SY => __('Syrian Arab Republic'),
            self::TW => __('Taiwan, Province of China'),
            self::TJ => __('Tajikistan'),
            self::TZ => __('Tanzania, United Republic of'),
            self::TH => __('Thailand'),
            self::TL => __('Timor-Leste'),
            self::TG => __('Togo'),
            self::TK => __('Tokelau'),
            self::TO => __('Tonga'),
            self::TT => __('Trinidad and Tobago'),
            self::TN => __('Tunisia'),
            self::TR => __('Türkiye'),
            self::TM => __('Turkmenistan'),
            self::TC => __('Turks and Caicos Islands'),
            self::TV => __('Tuvalu'),
            self::UG => __('Uganda'),
            self::UA => __('Ukraine'),
            self::AE => __('United Arab Emirates'),
            self::GB => __('United Kingdom of Great Britain and Northern Ireland'),
            self::US => __('United States of America'),
            self::UM => __('United States Minor Outlying Islands'),
            self::UY => __('Uruguay'),
            self::UZ => __('Uzbekistan'),
            self::VU => __('Vanuatu'),
            self::VE => __('Venezuela, Bolivarian Republic of'),
            self::VN => __('Viet Nam'),
            self::VG => __('Virgin Islands (British)'),
            self::VI => __('Virgin Islands (U.S.)'),
            self::WF => __('Wallis and Futuna'),
            self::EH => __('Western Sahara'),
            self::YE => __('Yemen'),
            self::ZM => __('Zambia'),
            self::ZW => __('Zimbabwe'),
        };
    }

    public function getFlagEmoji(): string
    {
        return match ($this) {
            self::AF => '🇦🇫',
            self::AX => '🇦🇽',
            self::AL => '🇦🇱',
            self::DZ => '🇩🇿',
            self::AS => '🇦🇸',
            self::AD => '🇦🇩',
            self::AO => '🇦🇴',
            self::AI => '🇦🇮',
            self::AQ => '🇦🇶',
            self::AG => '🇦🇬',
            self::AR => '🇦🇷',
            self::AM => '🇦🇲',
            self::AW => '🇦🇼',
            self::AU => '🇦🇺',
            self::AT => '🇦🇹',
            self::AZ => '🇦🇿',
            self::BS => '🇧🇸',
            self::BH => '🇧🇭',
            self::BD => '🇧🇩',
            self::BB => '🇧🇧',
            self::BY => '🇧🇾',
            self::BE => '🇧🇪',
            self::BZ => '🇧🇿',
            self::BJ => '🇧🇯',
            self::BM => '🇧🇲',
            self::BT => '🇧🇹',
            self::BO => '🇧🇴',
            self::BQ => '🇧🇶',
            self::BA => '🇧🇦',
            self::BW => '🇧🇼',
            self::BV => '🇧🇻',
            self::BR => '🇧🇷',
            self::IO => '🇮🇴',
            self::BN => '🇧🇳',
            self::BG => '🇧🇬',
            self::BF => '🇧🇫',
            self::BI => '🇧🇮',
            self::CV => '🇨🇻',
            self::KH => '🇰🇭',
            self::CM => '🇨🇲',
            self::CA => '🇨🇦',
            self::KY => '🇰🇾',
            self::CF => '🇨🇫',
            self::TD => '🇹🇩',
            self::CL => '🇨🇱',
            self::CN => '🇨🇳',
            self::CX => '🇨🇽',
            self::CC => '🇨🇨',
            self::CO => '🇨🇴',
            self::KM => '🇰🇲',
            self::CG => '🇨🇬',
            self::CD => '🇨🇩',
            self::CK => '🇨🇰',
            self::CR => '🇨🇷',
            self::CI => '🇨🇮',
            self::HR => '🇭🇷',
            self::CU => '🇨🇺',
            self::CW => '🇨🇼',
            self::CY => '🇨🇾',
            self::CZ => '🇨🇿',
            self::DK => '🇩🇰',
            self::DJ => '🇩🇯',
            self::DM => '🇩🇲',
            self::DO => '🇩🇴',
            self::EC => '🇪🇨',
            self::EG => '🇪🇬',
            self::SV => '🇸🇻',
            self::GQ => '🇬🇶',
            self::ER => '🇪🇷',
            self::EE => '🇪🇪',
            self::SZ => '🇸🇿',
            self::ET => '🇪🇹',
            self::FK => '🇫🇰',
            self::FO => '🇫🇴',
            self::FJ => '🇫🇯',
            self::FI => '🇫🇮',
            self::FR => '🇫🇷',
            self::GF => '🇬🇫',
            self::PF => '🇵🇫',
            self::TF => '🇹🇫',
            self::GA => '🇬🇦',
            self::GM => '🇬🇲',
            self::GE => '🇬🇪',
            self::DE => '🇩🇪',
            self::GH => '🇬🇭',
            self::GI => '🇬🇮',
            self::GR => '🇬🇷',
            self::GL => '🇬🇱',
            self::GD => '🇬🇩',
            self::GP => '🇬🇵',
            self::GU => '🇬🇺',
            self::GT => '🇬🇹',
            self::GG => '🇬🇬',
            self::GN => '🇬🇳',
            self::GW => '🇬🇼',
            self::GY => '🇬🇾',
            self::HT => '🇭🇹',
            self::HM => '🇭🇲',
            self::VA => '🇻🇦',
            self::HN => '🇭🇳',
            self::HK => '🇭🇰',
            self::HU => '🇭🇺',
            self::IS => '🇮🇸',
            self::IN => '🇮🇳',
            self::ID => '🇮🇩',
            self::IR => '🇮🇷',
            self::IQ => '🇮🇶',
            self::IE => '🇮🇪',
            self::IM => '🇮🇲',
            self::IL => '🇮🇱',
            self::IT => '🇮🇹',
            self::JM => '🇯🇲',
            self::JP => '🇯🇵',
            self::JE => '🇯🇪',
            self::JO => '🇯🇴',
            self::KZ => '🇰🇿',
            self::KE => '🇰🇪',
            self::KI => '🇰🇮',
            self::KP => '🇰🇵',
            self::KR => '🇰🇷',
            self::KW => '🇰🇼',
            self::KG => '🇰🇬',
            self::LA => '🇱🇦',
            self::LV => '🇱🇻',
            self::LB => '🇱🇧',
            self::LS => '🇱🇸',
            self::LR => '🇱🇷',
            self::LY => '🇱🇾',
            self::LI => '🇱🇮',
            self::LT => '🇱🇹',
            self::LU => '🇱🇺',
            self::MO => '🇲🇴',
            self::MG => '🇲🇬',
            self::MW => '🇲🇼',
            self::MY => '🇲🇾',
            self::MV => '🇲🇻',
            self::ML => '🇲🇱',
            self::MT => '🇲🇹',
            self::MH => '🇲🇭',
            self::MQ => '🇲🇶',
            self::MR => '🇲🇷',
            self::MU => '🇲🇺',
            self::YT => '🇾🇹',
            self::MX => '🇲🇽',
            self::FM => '🇫🇲',
            self::MD => '🇲🇩',
            self::MC => '🇲🇨',
            self::MN => '🇲🇳',
            self::ME => '🇲🇪',
            self::MS => '🇲🇸',
            self::MA => '🇲🇦',
            self::MZ => '🇲🇿',
            self::MM => '🇲🇲',
            self::NA => '🇳🇦',
            self::NR => '🇳🇷',
            self::NP => '🇳🇵',
            self::NL => '🇳🇱',
            self::NC => '🇳🇨',
            self::NZ => '🇳🇿',
            self::NI => '🇳🇮',
            self::NE => '🇳🇪',
            self::NG => '🇳🇬',
            self::NU => '🇳🇺',
            self::NF => '🇳🇫',
            self::MK => '🇲🇰',
            self::MP => '🇲🇵',
            self::NO => '🇳🇴',
            self::OM => '🇴🇲',
            self::PK => '🇵🇰',
            self::PW => '🇵🇼',
            self::PS => '🇵🇸',
            self::PA => '🇵🇦',
            self::PG => '🇵🇬',
            self::PY => '🇵🇾',
            self::PE => '🇵🇪',
            self::PH => '🇵🇭',
            self::PN => '🇵🇳',
            self::PL => '🇵🇱',
            self::PT => '🇵🇹',
            self::PR => '🇵🇷',
            self::QA => '🇶🇦',
            self::RE => '🇷🇪',
            self::RO => '🇷🇴',
            self::RU => '🇷🇺',
            self::RW => '🇷🇼',
            self::BL => '🇧🇱',
            self::SH => '🇸🇭',
            self::KN => '🇰🇳',
            self::LC => '🇱🇨',
            self::MF => '🇲🇫',
            self::PM => '🇵🇲',
            self::VC => '🇻🇨',
            self::WS => '🇼🇸',
            self::SM => '🇸🇲',
            self::ST => '🇸🇹',
            self::SA => '🇸🇦',
            self::SN => '🇸🇳',
            self::RS => '🇷🇸',
            self::SC => '🇸🇨',
            self::SL => '🇸🇱',
            self::SG => '🇸🇬',
            self::SX => '🇸🇽',
            self::SK => '🇸🇰',
            self::SI => '🇸🇮',
            self::SB => '🇸🇧',
            self::SO => '🇸🇴',
            self::ZA => '🇿🇦',
            self::GS => '🇬🇸',
            self::SS => '🇸🇸',
            self::ES => '🇪🇸',
            self::LK => '🇱🇰',
            self::SD => '🇸🇩',
            self::SR => '🇸🇷',
            self::SJ => '🇸🇯',
            self::SE => '🇸🇪',
            self::CH => '🇨🇭',
            self::SY => '🇸🇾',
            self::TW => '🇹🇼',
            self::TJ => '🇹🇯',
            self::TZ => '🇹🇿',
            self::TH => '🇹🇭',
            self::TL => '🇹🇱',
            self::TG => '🇹🇬',
            self::TK => '🇹🇰',
            self::TO => '🇹🇴',
            self::TT => '🇹🇹',
            self::TN => '🇹🇳',
            self::TR => '🇹🇷',
            self::TM => '🇹🇲',
            self::TC => '🇹🇨',
            self::TV => '🇹🇻',
            self::UG => '🇺🇬',
            self::UA => '🇺🇦',
            self::AE => '🇦🇪',
            self::GB => '🇬🇧',
            self::US => '🇺🇸',
            self::UM => '🇺🇲',
            self::UY => '🇺🇾',
            self::UZ => '🇺🇿',
            self::VU => '🇻🇺',
            self::VE => '🇻🇪',
            self::VN => '🇻🇳',
            self::VG => '🇻🇬',
            self::VI => '🇻🇮',
            self::WF => '🇼🇫',
            self::EH => '🇪🇭',
            self::YE => '🇾🇪',
            self::ZM => '🇿🇲',
            self::ZW => '🇿🇼',
        };
    }

    public function getLabel(): string|Htmlable|null
    {
        return $this->getFlagEmoji() . ' ' . $this->getName();
    }

}
